codes : god reporter hare turtle

god : god.cpp
	g++ -std=c++11 -o god god.cpp

reporter : reporter.cpp
	g++ -std=c++11 -o reporter reporter.cpp

hare : hare.cpp
	g++ -std=c++11 -o hare hare.cpp

turtle : turtle.cpp
	g++ -std=c++11 -o turtle turtle.cpp

clean:
	rm -f god reporter turtle hare
	echo cleaned